/* tslint:disable */
/* eslint-disable */
/**
 * MIPH Shop Public API
 * Public-facing API for the MIPH educational shop backend.  ## Highlights - Magic-link authentication (no passwords) - Catalog browsing with filters and pagination - Likes, cart sync, and checkout flows - Consistent error envelope `{ error: { code, message, details } }`  ## Conventions - Base path: `/api/v1` - JSON: camelCase - Monetary fields are floats (RUB) in API responses - Pagination: `page`, `perPage` with `total` and `totalPages` 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

